# ------------------------- USERS -------------------------
# Get the list of Users
GET http://127.0.0.1:8080/users/

# Get a specific User by its id
GET http://127.0.0.1:8080/users/1

# User not found
GET http://127.0.0.1:8080/users/9999

POST http://127.0.0.1:8080/users/ HTTP/1.1
Content-Type: application/json

{
    "name": "Mario",
    "surname": "Red",
    "email": "mario.red@somecompany.com",
    "password": "Some password"
}

# ------------------------- CUSTOMERS -------------------------

# Get the list of Customers
GET http://127.0.0.1:8080/customers/

# Get a specific Customer by its id
GET http://127.0.0.1:8080/customers/1

# Customer not found
GET http://127.0.0.1:8080/customers/9999

# Creates a new customer
POST http://127.0.0.1:8080/customers/ HTTP/1.1
Content-Type: application/json

{
    "name": "Yo Customer"    
}

# ------------------------- JOBS -------------------------

# Get the list of Jobs
GET http://127.0.0.1:8080/jobs/

# Get a specific Jobs by its id
GET http://127.0.0.1:8080/jobs/1

# Job not found
GET http://127.0.0.1:8080/jobs/9999

# Creates a new job
POST http://127.0.0.1:8080/jobs/ HTTP/1.1
Content-Type: application/json

{
    "name": "JOB001",
    "description": "This is a new job",
    "customer_id": 1
}

# ------------------------- DOCUMENTS -------------------------

# Get the list of Documents
GET http://127.0.0.1:8080/documents/

# Get a specific Document by its id
GET http://127.0.0.1:8080/documents/1

# Document not found
GET http://127.0.0.1:8080/documents/9999

# Creates a new document
POST http://127.0.0.1:8080/documents/ HTTP/1.1
Content-Type: application/json

{
    "name": "DOC001",
    "description": "This is a new document",
    "job_id": 3
}

# ------------------------- REVISIONS -------------------------

# Get the list of Revisions
GET http://127.0.0.1:8080/revisions/

# Get a specific Revision by its id
GET http://127.0.0.1:8080/revisions/1

# Revision not found
GET http://127.0.0.1:8080/revisions/9999

POST http://127.0.0.1:8080/revisions/ HTTP/1.1
Content-Type: application/json

{
    "version": "REV001",
    "description": "First release",
    "file_path": "\\someserver\\somefolder\\somefile.docx",
    "user_id": 2,
    "document_id": 4
}

POST http://127.0.0.1:8080/revisions/ HTTP/1.1
Content-Type: application/json

{
    "version": "REV002",
    "description": "Updated some text in some page",
    "file_path": "\\someserver\\somefolder\\somefile.docx",
    "user_id": 1,
    "document_id": 4
}